// Generated by dts-bundle-generator v9.5.1

import { ReactNode } from 'react';

export type NormalizedFn = {
	(props: Record<string, unknown>): string;
	normalized: true;
};
export type RawValue = string | ((props: Record<string, unknown>) => string) | NormalizedFn;
export type RawEntry = Record<string, RawValue>;
export type Dictionary = Record<string, RawEntry>;
declare const _default: ({ language: lang, dictionary: dict, children, render, component, ...props }: {
	language?: string;
	dictionary?: Dictionary;
	children?: ReactNode;
	render?: (text: string) => ReactNode;
	component?: ReactNode;
	id?: string;
	[key: string]: unknown;
}) => string | number | boolean | Iterable<ReactNode> | import("react/jsx-runtime").JSX.Element | null | undefined;

export {
	_default as default,
};

export {};
